services:

  database:
    env_file:
      - .env
    healthcheck:
      interval: 1s
      test: 'pg_isready --username=postgres'
    image: postgres
    command: >
      /bin/bash -c "echo 'listen_addresses='*' >> /var/lib/postgresql/data/postgresql.conf && docker-entrypoint.sh postgres"
    volumes:
      - ./data:/var/lib/postgresql/data

  backend:
    build: backend
    depends_on:
      - database
    env_file:
      - .env
    ports:
      - "3000:3000"

  frontend:
    build: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
